[package]
name = "rinha-knn"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2", features = ["napi6"] }
napi-derive = "2"
aligned-vec = "0.6"
flate2 = { version = "1", default-features = false, features = ["rust_backend"] }

[build-dependencies]
napi-build = "2"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = false
